version: "3.8"
services:
  app:
    container_name: sticker_smash_app
    tty: true
    build:
      context: .
      dockerfile: sticker_smash_app/Dockerfile
    volumes:
      - .:/home/StickerSmashStudy
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
